### ISSUE TITLE
Matplotlib.show() with Cpython

### ISSUE THREAD

**Issue by SBCV** [fferflo/semantic-meshes#4]
With the current cpython installation, it is not possible to use matplotlib's `show()` method.
For example, running
```
import matplotlib.pyplot as plt
plt.plot([1,2,3],[5,7,4])
plt.show()
```
will throw `UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.`

To add the `tinker` gui backend on Ubuntu for the custom `cpython` installation (after `install.sh` has already been executed) just run:
```
sudo apt-get install tk-dev
cd /path/to/cpython/build/dir
make -j
make install -j
```

Maybe it would be useful to add this to the documentation.

**Comment by fferflo** [comment]
Thanks for the info! I update the readme with a comment for optional python dependencies.
